#!/usr/bin/env bash
set -eo pipefail

readonly message="${1:-goal}"

echo "Setting up goal for: '$message'"
git commit --allow-empty --no-verify -m "$message" > /dev/null 2>&1

echo "Run 'git done' when you're finished."
